### ISSUE TITLE
Testing the bot locally 

### ISSUE THREAD

**Issue by manu-chroma** [pavitrakumar78/Python-telegram-bot-GetPDFbot#1]
Hey, is there any way to test the bot locally i.e. without deploying on google app engine? Thanks.

**Comment by pavitrakumar78** [comment]
Note: I am no longer working on this. The library I have used in this and the Telegram API might be different now. 

But you should be possible to test the app easily in python itself. Just take in a message as user input (i.e. `message` variable in `main.py` file) and see what the program returns. This might need some modifications in the `main.py` file. I do not know of a way to test program in the app without deploying it to GAE.

**Comment by manu-chroma** [comment]
thanks so much.
